### ISSUE TITLE
Chrome extensions run no tests and there's no instructions on how to use the artifacts

### ISSUE THREAD

**Issue by posix4e** [Technodroidz/ExtensionApp#8]
Run npm test

> chrome-extapp-package@1.0.1 test /home/runner/work/ExtensionApp/ExtensionApp/ChromeExtApp
> echo "Running tests for Chrome Extension App..." && exit 0

Running tests for Chrome Extension App...

Please add to the README, how to load this chrome extension

**Comment by vikash279** [comment]
Fixed
